# Generated by Django 4.1.3 on 2022-12-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_profile_blogname_alter_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blogname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
