# Generated by Django 4.1.3 on 2023-01-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_profile_blogname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introduce',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
