# Generated by Django 4.1.3 on 2022-11-17 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footstep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='footstep.post'),
            preserve_default=False,
        ),
    ]
