# Generated by Django 4.1.3 on 2022-12-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footstep', '0004_alter_post_subject_alter_sidebarcontent_category_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sidebarcontent',
            name='category_sub',
            field=models.CharField(max_length=200),
        ),
    ]
