# Generated by Django 4.1.3 on 2022-12-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footstep', '0007_remove_comment_recommend_remove_post_recommend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sidebarcontent',
            name='category_sub',
            field=models.CharField(max_length=150),
        ),
    ]
