# Generated by Django 4.1.3 on 2022-12-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footstep', '0008_post_subtitle_alter_post_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
